// Obligation files: one committed YAML file per Agreed MUST or MUST
// NOT requirement under .same-page/obligations/, keyed on the
// requirement identifier (ENG-012, ENG-013, ENG-187, ENG-188). The
// derived fields are regenerated by elaboration; profile and
// validators are the developer's to set and survive re-elaboration
// (ENG-217).

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { digest } from "./digest.ts";
import { inheritedProfile, type Finding, type Policy } from "./policy.ts";
import type { Requirement } from "./specs.ts";
import { parseYaml, stringifyYaml, type YamlMap, type YamlValue } from "./yaml.ts";

export type Obligation = {
  requirement: string;
  locator: string;
  keyword: "MUST" | "MUST NOT";
  requirement_digest: string;
  falsifier: string;
  falsifier_digest: string;
  profile: string;
  profile_from: string; // "project default", "domain <PREFIX>", or "obligation" (set by hand)
  validators: YamlValue[];
  sentence: string;
};

export const OBLIGATION_HEADER = [
  "Same Page obligation. The derived fields (locator, digests, falsifier,",
  "sentence, profile_from) are regenerated by `same-page elaborate` from the",
  "spec and the policy; profile and validators are yours to set and survive",
  "re-elaboration. A profile you set is marked profile_from: obligation.",
];

const FIELDS = ["requirement", "locator", "keyword", "requirement_digest", "falsifier", "falsifier_digest", "profile", "profile_from", "validators", "sentence"] as const;

export function obligationsDir(root: string): string {
  return join(root, ".same-page", "obligations");
}

export function obligationPath(root: string, id: string): string {
  return join(obligationsDir(root), `${id}.yaml`);
}

export function locatorOf(req: Requirement): string {
  return `${req.file}::${req.id}`;
}

// Build the obligation a requirement projects to. The profile is the
// nearest inherited default (ENG-077) unless the developer set one on
// the file (ENG-217): a profile that differs from the inherited one,
// names a defined profile, and was not left behind by a policy change
// is the developer's and is kept, marked `profile_from: obligation`.
export function projectObligation(req: Requirement, policy: Policy, existing: Obligation | null): Obligation {
  if (req.keyword !== "MUST" && req.keyword !== "MUST NOT") throw new Error(`${req.id} carries no obligation keyword`);
  if (req.falsifier === null) throw new Error(`${req.id} has no confirmed falsifier`);
  const inherited = inheritedProfile(policy, req.prefix);
  let profile = inherited.name;
  let from = inherited.source;
  let validators: YamlValue[] = [];
  if (existing) {
    validators = existing.validators;
    const defined = Object.prototype.hasOwnProperty.call(policy.profiles, existing.profile);
    if (existing.profile_from === "obligation") {
      profile = existing.profile;
      from = "obligation";
    } else if (existing.profile !== inherited.name && defined && (existing.profile_from === "" || existing.profile_from === inherited.source)) {
      profile = existing.profile;
      from = "obligation";
    }
  }
  return {
    requirement: req.id,
    locator: locatorOf(req),
    keyword: req.keyword,
    requirement_digest: digest(req.text),
    falsifier: req.falsifier,
    falsifier_digest: digest(req.falsifier),
    profile,
    profile_from: from,
    validators,
    sentence: req.text,
  };
}

export function obligationText(o: Obligation): string {
  const map: YamlMap = {};
  for (const f of FIELDS) map[f] = o[f] as YamlValue;
  return stringifyYaml(map, OBLIGATION_HEADER);
}

export function readObligation(path: string, where: string): { obligation: Obligation | null; findings: Finding[] } {
  const findings: Finding[] = [];
  let raw: YamlValue;
  try {
    raw = parseYaml(readFileSync(path, "utf8"));
  } catch (e) {
    return { obligation: null, findings: [{ where, message: (e as Error).message, rule: "ENG-188" }] };
  }
  if (raw === null || typeof raw !== "object" || Array.isArray(raw))
    return { obligation: null, findings: [{ where, message: "an obligation file is a mapping", rule: "ENG-015" }] };
  const m = raw as YamlMap;
  const str = (k: string): string | null => (typeof m[k] === "string" ? (m[k] as string) : null);
  const missing = ["requirement", "locator", "requirement_digest", "falsifier", "falsifier_digest"].filter((k) => str(k) === null || str(k) === "");
  if (missing.length) findings.push({ where, message: `missing field(s): ${missing.join(", ")}`, rule: "ENG-015" });
  const keyword = str("keyword");
  if (keyword !== "MUST" && keyword !== "MUST NOT") findings.push({ where, message: "keyword must be MUST or MUST NOT", rule: "ENG-024" });
  const profile = str("profile");
  if (profile === null || profile === "") findings.push({ where, message: "missing field: profile", rule: "ENG-016" });
  const validators = m["validators"];
  if (!Array.isArray(validators)) findings.push({ where, message: "validators must be a list", rule: "ENG-016" });
  for (const k of Object.keys(m)) if (!(FIELDS as readonly string[]).includes(k)) findings.push({ where, message: `unknown field ${k}`, rule: "ENG-015" });
  if (findings.length) return { obligation: null, findings };
  return {
    obligation: {
      requirement: str("requirement")!,
      locator: str("locator")!,
      keyword: keyword as "MUST" | "MUST NOT",
      requirement_digest: str("requirement_digest")!,
      falsifier: str("falsifier")!,
      falsifier_digest: str("falsifier_digest")!,
      profile: profile!,
      profile_from: str("profile_from") ?? "",
      validators: validators as YamlValue[],
      sentence: str("sentence") ?? "",
    },
    findings,
  };
}

// Write only when the content changes, so re-elaboration is idempotent
// and a clean tree stays clean.
export function writeObligation(path: string, o: Obligation): boolean {
  const text = obligationText(o);
  if (existsSync(path) && readFileSync(path, "utf8") === text) return false;
  writeFileSync(path, text);
  return true;
}
