// Obligation files: one committed YAML file per Agreed MUST or MUST
// NOT requirement under .same-page/obligations/, keyed on the
// requirement identifier (ENG-012, ENG-013, ENG-187, ENG-188). The
// derived fields are regenerated by elaboration; profile and
// validators are the developer's to set and survive re-elaboration
// (ENG-217).

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { digest } from "./digest.ts";
import { compareStrength, inheritedProfile, parseProfile, requireToYaml, type Finding, type Policy, type Profile } from "./policy.ts";
import type { Requirement } from "./specs.ts";
import { parseYaml, stringifyYaml, type YamlMap, type YamlValue } from "./yaml.ts";

// A validator reference on an obligation: the mapping from requirement
// to mechanism. A bare name is a mapping nobody vouched for
// (binding_basis none); attested_by makes it an attested binding
// (ENG-030), and elaboration completes the timestamp and snapshot.
export type ValidatorRef = {
  name: string;
  attested_by?: "developer" | "agent";
  actor?: string;
  attested_at?: string;
  snapshot?: string;
  developer_confirmed?: boolean;
};

export type Obligation = {
  requirement: string;
  locator: string;
  keyword: "MUST" | "MUST NOT";
  requirement_digest: string;
  falsifier: string;
  falsifier_digest: string;
  profile: string;
  profile_from: string; // "project default", "domain <PREFIX>", or "obligation" (set by hand)
  required: Profile["require"]; // the clauses the profile demanded at elaboration (ENG-101 baseline)
  validators: ValidatorRef[];
  sentence: string;
};

export const OBLIGATION_HEADER = [
  "Same Page obligation. The derived fields (locator, digests, falsifier,",
  "sentence, profile_from, required) are regenerated by `same-page elaborate`",
  "from the spec and the policy; profile and validators are yours to set and",
  "survive re-elaboration. A profile you set is marked profile_from:",
  "obligation. A validators entry is `- name: <validator>`, plus",
  "`attested_by: developer` (or agent) to vouch for the mapping.",
];

const FIELDS = ["requirement", "locator", "keyword", "requirement_digest", "falsifier", "falsifier_digest", "profile", "profile_from", "required", "validators", "sentence"] as const;

export function obligationsDir(root: string): string {
  return join(root, ".same-page", "obligations");
}

export function obligationPath(root: string, id: string): string {
  return join(obligationsDir(root), `${id}.yaml`);
}

export function locatorOf(req: Requirement): string {
  return `${req.file}::${req.id}`;
}

// Build the obligation a requirement projects to. The profile is the
// nearest inherited default (ENG-077) unless the developer set one on
// the file (ENG-217): a profile that differs from the inherited one,
// names a defined profile, and was not left behind by a policy change
// is the developer's and is kept, marked `profile_from: obligation`.
export type Projection = { obligation: Obligation; downgrade: { old: Profile["require"]; new: Profile["require"] } | null };

export function projectObligation(req: Requirement, policy: Policy, existing: Obligation | null, snapshot: string, actor: string): Projection {
  if (req.keyword !== "MUST" && req.keyword !== "MUST NOT") throw new Error(`${req.id} carries no obligation keyword`);
  if (req.falsifier === null) throw new Error(`${req.id} has no confirmed falsifier`);
  const inherited = inheritedProfile(policy, req.prefix);
  let profile = inherited.name;
  let from = inherited.source;
  let validators: ValidatorRef[] = [];
  if (existing) {
    validators = existing.validators.map((v) => completeRef(v, snapshot, actor));
    const defined = Object.prototype.hasOwnProperty.call(policy.profiles, existing.profile);
    if (existing.profile_from === "obligation") {
      profile = existing.profile;
      from = "obligation";
    } else if (existing.profile !== inherited.name && defined && (existing.profile_from === "" || existing.profile_from === inherited.source)) {
      profile = existing.profile;
      from = "obligation";
    }
  }
  // ENG-101: the clauses the profile demands now, against what the
  // obligation last recorded. Equal or stronger is taken; weaker is a
  // downgrade that holds the old baseline until the developer confirms.
  const current = policy.profiles[profile]?.require ?? { any: [] };
  let required = current;
  let downgrade: Projection["downgrade"] = null;
  if (existing && Object.keys(existing.required).length && Object.prototype.hasOwnProperty.call(policy.profiles, profile)) {
    const cmp = compareStrength(existing.required, current);
    if (cmp === "weaker") {
      required = existing.required;
      downgrade = { old: existing.required, new: current };
    }
  }
  return {
    obligation: {
      requirement: req.id,
      locator: locatorOf(req),
      keyword: req.keyword,
      requirement_digest: digest(req.text),
      falsifier: req.falsifier,
      falsifier_digest: digest(req.falsifier),
      profile,
      profile_from: from,
      required,
      validators,
      sentence: req.text,
    },
    downgrade,
  };
}

export function completeRef(v: ValidatorRef, snapshot: string, actor: string): ValidatorRef {
  if (!v.attested_by) return { name: v.name };
  return {
    name: v.name,
    attested_by: v.attested_by,
    actor: v.actor ?? actor,
    attested_at: v.attested_at ?? new Date().toISOString(),
    snapshot: v.snapshot ?? snapshot,
    developer_confirmed: v.developer_confirmed ?? v.attested_by === "developer",
  };
}

function refToYaml(v: ValidatorRef): YamlMap {
  const m: YamlMap = { name: v.name };
  if (v.attested_by) {
    m["attested_by"] = v.attested_by;
    if (v.actor !== undefined) m["actor"] = v.actor;
    if (v.attested_at !== undefined) m["attested_at"] = v.attested_at;
    if (v.snapshot !== undefined) m["snapshot"] = v.snapshot;
    m["developer_confirmed"] = v.developer_confirmed ?? false;
  }
  return m;
}

function parseRef(raw: YamlValue, where: string, findings: Finding[]): ValidatorRef | null {
  if (typeof raw === "string") return { name: raw };
  if (raw === null || typeof raw !== "object" || Array.isArray(raw) || typeof raw["name"] !== "string") {
    findings.push({ where, message: "a validators entry is a name or a mapping with a name", rule: "ENG-016" });
    return null;
  }
  const ref: ValidatorRef = { name: raw["name"] as string };
  const ab = raw["attested_by"];
  if (ab !== undefined) {
    if (ab !== "developer" && ab !== "agent") {
      findings.push({ where, message: `attested_by must be developer or agent`, rule: "ENG-030" });
      return null;
    }
    ref.attested_by = ab;
    if (typeof raw["actor"] === "string") ref.actor = raw["actor"] as string;
    if (typeof raw["attested_at"] === "string") ref.attested_at = raw["attested_at"] as string;
    if (typeof raw["snapshot"] === "string") ref.snapshot = raw["snapshot"] as string;
    if (typeof raw["developer_confirmed"] === "boolean") ref.developer_confirmed = raw["developer_confirmed"] as boolean;
  }
  return ref;
}

export function obligationText(o: Obligation): string {
  const map: YamlMap = {};
  for (const f of FIELDS) {
    if (f === "required") map[f] = requireToYaml(o.required);
    else if (f === "validators") map[f] = o.validators.map(refToYaml);
    else map[f] = o[f] as YamlValue;
  }
  return stringifyYaml(map, OBLIGATION_HEADER);
}

export function readObligation(path: string, where: string): { obligation: Obligation | null; findings: Finding[] } {
  const findings: Finding[] = [];
  let raw: YamlValue;
  try {
    raw = parseYaml(readFileSync(path, "utf8"));
  } catch (e) {
    return { obligation: null, findings: [{ where, message: (e as Error).message, rule: "ENG-188" }] };
  }
  if (raw === null || typeof raw !== "object" || Array.isArray(raw))
    return { obligation: null, findings: [{ where, message: "an obligation file is a mapping", rule: "ENG-015" }] };
  const m = raw as YamlMap;
  const str = (k: string): string | null => (typeof m[k] === "string" ? (m[k] as string) : null);
  const missing = ["requirement", "locator", "requirement_digest", "falsifier", "falsifier_digest"].filter((k) => str(k) === null || str(k) === "");
  if (missing.length) findings.push({ where, message: `missing field(s): ${missing.join(", ")}`, rule: "ENG-015" });
  const keyword = str("keyword");
  if (keyword !== "MUST" && keyword !== "MUST NOT") findings.push({ where, message: "keyword must be MUST or MUST NOT", rule: "ENG-024" });
  const profile = str("profile");
  if (profile === null || profile === "") findings.push({ where, message: "missing field: profile", rule: "ENG-016" });
  const validatorsRaw = m["validators"];
  const validators: ValidatorRef[] = [];
  if (!Array.isArray(validatorsRaw)) findings.push({ where, message: "validators must be a list", rule: "ENG-016" });
  else for (const v of validatorsRaw) {
    const ref = parseRef(v, where, findings);
    if (ref) validators.push(ref);
  }
  let required: Profile["require"] = {};
  if (m["required"] !== undefined) {
    const parsed = parseProfile({ require: m["required"] }, `${where}:required`, findings);
    if (parsed) required = parsed.require;
  }
  for (const k of Object.keys(m)) if (!(FIELDS as readonly string[]).includes(k)) findings.push({ where, message: `unknown field ${k}`, rule: "ENG-015" });
  if (findings.length) return { obligation: null, findings };
  return {
    obligation: {
      requirement: str("requirement")!,
      locator: str("locator")!,
      keyword: keyword as "MUST" | "MUST NOT",
      requirement_digest: str("requirement_digest")!,
      falsifier: str("falsifier")!,
      falsifier_digest: str("falsifier_digest")!,
      profile: profile!,
      profile_from: str("profile_from") ?? "",
      required,
      validators,
      sentence: str("sentence") ?? "",
    },
    findings,
  };
}

// Write only when the content changes, so re-elaboration is idempotent
// and a clean tree stays clean.
export function writeObligation(path: string, o: Obligation): boolean {
  const text = obligationText(o);
  if (existsSync(path) && readFileSync(path, "utf8") === text) return false;
  writeFileSync(path, text);
  return true;
}
