#!/usr/bin/env node
// scripts/cutlist.mjs: read the 1.x spec files and write the cut list.
//   node scripts/cutlist.mjs <1.x docs/spec dir> > docs/cutover/cut-list.md
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

export const FAMILY = {
  LOOP: ["replaced-by-predicate", "the section 5 predicates, precedence and Done rule replace the loop requirements; markdown records, stop records, explain, present and reword are removed (section 12)"],
  SPEC: ["kept", "agreement per block, falsifiers before Agreed, lint as the grammar's falsifier and the spec-phase tail continue; promotion never Agrees text (13.9)"],
  PKG: ["replaced-by-predicate", "hooks (section 6) and distribution (section 11) keep the intent; stop-hook refusal, refusal counts, kernel-digest freshness and package lint are removed (section 12)"],
  DEC: ["kept", "two kernel levels, the canonical ADR, the read queue and supersession causes continue; the four-level scale and Judged files are removed (section 12)"],
  AUTO: ["removed", "the autonomy and former Jev modes were Agreed but never built (section 12); section 10's evaluator is a different contract"],
};

export function cutlist(specDir) {
  const families = [], rows = [];
  for (const file of readdirSync(specDir).filter((f) => f.endsWith(".md")).sort()) {
    const text = readFileSync(join(specDir, file), "utf8");
    const prefix = /^Prefix:\s*([A-Z]+)/m.exec(text)?.[1];
    const ids = [];
    let section = "";
    for (const line of text.split("\n")) {
      const h = /^##+\s+(.*)$/.exec(line); if (h) { section = h[1].trim(); continue; }
      const m = /^\[([A-Z]+)-(\d+)\]/.exec(line); if (!m) continue;
      const fam = m[1];
      if (!FAMILY[fam]) throw new Error(`unknown 1.x family ${fam} in ${file}`);
      ids.push(`${fam}-${m[2]}`);
      rows.push({ id: `${fam}-${m[2]}`, file, section, disposition: FAMILY[fam][0] });
    }
    if (ids.length) families.push({ prefix: prefix ?? ids[0].split("-")[0], file, count: ids.length, ids });
  }
  families.sort((a, b) => (a.prefix < b.prefix ? -1 : 1));
  return { families, rows };
}

export function render({ families, rows }) {
  const out = ["# Sudus 1.x cut list", "", "Generated by scripts/cutlist.mjs from the 1.x docs/spec files. Section 12 of docs/spec/sudus-v2.md is the authority; a row corrected by hand says so in its reason column.", "", "## Families", "", "| Family | 1.x file | Blocks | Disposition | Reason |", "|---|---|---|---|---|"];
  for (const f of families) out.push(`| ${f.prefix} | ${f.file} | ${f.count} | ${FAMILY[f.prefix][0]} | ${FAMILY[f.prefix][1]} |`);
  out.push("", "## Identifiers", "", "| Identifier | File | 1.x section | Disposition |", "|---|---|---|---|");
  for (const r of rows) out.push(`| ${r.id} | ${r.file} | ${r.section} | ${r.disposition} |`);
  return out.join("\n") + "\n";
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  process.stdout.write(render(cutlist(process.argv[2])));
}
